service: rsschool-s3-service


provider: 
  name: aws
  runtime: nodejs14.x
  region: "eu-west-1"

  iamRoleStatements: 
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: 
        - "arn:aws:s3:::rsschool-s3-service"
    - Effect: "Allow"
      Action: 
        - "s3:*"
      Resource: 
        - "arn:aws:s3:::rsschool-s3-service/*"    

functions: 
  importProductsFile:
    handler: handler.importProductsFile
    events:  
      - http: 
          method: GET
          path: "import/"
          request: 
            parameters:
              querystrings: 
                name: true
  importFileParser:
    handler: handler.importFileParser
    events: 
      - s3: 
          bucket: rsschool-s3-service
          event: s3:ObjectCreated:*
          rules:
            - prefix: 'uploaded/'
          existing: true  