service: rsschool-s3-service


provider: 
  name: aws
  runtime: nodejs14.x
  region: "eu-west-1"

  iamRoleStatements: 
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: 
        - "arn:aws:s3:::rsschool-s3-service"
    - Effect: "Allow"
      Action: 
        - "s3:*"
      Resource: 
        - "arn:aws:s3:::rsschool-s3-service/*"    

functions: 
  getFiles:
    handler: handler.getFiles
    events:  
      - http: 
          method: GET
          path: "files/"